// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/option_example.proto

package com.example.options;

public interface OptionMessageOtherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.options.OptionMessageOther)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string hello = 1;</code>
   * @return The hello.
   */
  java.lang.String getHello();
  /**
   * <code>string hello = 1;</code>
   * @return The bytes for hello.
   */
  com.google.protobuf.ByteString
      getHelloBytes();
}
