// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/option_example.proto

package com.example.options;

public final class OptionExample {
  private OptionExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
