// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/enum_example.proto

package example.enumerations;

public final class EnumExample {
  private EnumExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code example.enumerations.DayOfTheWeek}
   */
  public enum DayOfTheWeek
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURSDAY = 4;</code>
     */
    THURSDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    /**
     * <code>SUNDAY = 7;</code>
     */
    SUNDAY(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURSDAY = 4;</code>
     */
    public static final int THURSDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;
    /**
     * <code>SUNDAY = 7;</code>
     */
    public static final int SUNDAY_VALUE = 7;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfTheWeek valueOf(int value) {
      return forNumber(value);
    }

    public static DayOfTheWeek forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURSDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        case 7: return SUNDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfTheWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>() {
            @java.lang.Override
            public DayOfTheWeek findValueByNumber(int number) {
              return DayOfTheWeek.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return DayOfTheWeekVerifier.INSTANCE;
    }

    private static final class DayOfTheWeekVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DayOfTheWeekVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return DayOfTheWeek.forNumber(number) != null;
            }
          };

    private final int value;

    private DayOfTheWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:example.enumerations.DayOfTheWeek)
  }

  public interface EnumMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.enumerations.EnumMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The enum numeric value on the wire for dayOfTheWeek.
     */
    int getDayOfTheWeekValue();
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The dayOfTheWeek.
     */
    example.enumerations.EnumExample.DayOfTheWeek getDayOfTheWeek();
  }
  /**
   * Protobuf type {@code example.enumerations.EnumMessage}
   */
  public  static final class EnumMessage extends
      com.google.protobuf.GeneratedMessageLite<
          EnumMessage, EnumMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:example.enumerations.EnumMessage)
      EnumMessageOrBuilder {
    private EnumMessage() {
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int DAY_OF_THE_WEEK_FIELD_NUMBER = 2;
    private int dayOfTheWeek_;
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The enum numeric value on the wire for dayOfTheWeek.
     */
    @java.lang.Override
    public int getDayOfTheWeekValue() {
      return dayOfTheWeek_;
    }
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @return The dayOfTheWeek.
     */
    @java.lang.Override
    public example.enumerations.EnumExample.DayOfTheWeek getDayOfTheWeek() {
      example.enumerations.EnumExample.DayOfTheWeek result = example.enumerations.EnumExample.DayOfTheWeek.forNumber(dayOfTheWeek_);
      return result == null ? example.enumerations.EnumExample.DayOfTheWeek.UNRECOGNIZED : result;
    }
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @param value The enum numeric value on the wire for dayOfTheWeek to set.
     */
    private void setDayOfTheWeekValue(int value) {
        dayOfTheWeek_ = value;
    }
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     * @param value The dayOfTheWeek to set.
     */
    private void setDayOfTheWeek(example.enumerations.EnumExample.DayOfTheWeek value) {
      dayOfTheWeek_ = value.getNumber();
      
    }
    /**
     * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
     */
    private void clearDayOfTheWeek() {
      
      dayOfTheWeek_ = 0;
    }

    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static example.enumerations.EnumExample.EnumMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static example.enumerations.EnumExample.EnumMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static example.enumerations.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(example.enumerations.EnumExample.EnumMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code example.enumerations.EnumMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          example.enumerations.EnumExample.EnumMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:example.enumerations.EnumMessage)
        example.enumerations.EnumExample.EnumMessageOrBuilder {
      // Construct using example.enumerations.EnumExample.EnumMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
       * @return The enum numeric value on the wire for dayOfTheWeek.
       */
      @java.lang.Override
      public int getDayOfTheWeekValue() {
        return instance.getDayOfTheWeekValue();
      }
      /**
       * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
       * @param value The dayOfTheWeek to set.
       * @return This builder for chaining.
       */
      public Builder setDayOfTheWeekValue(int value) {
        copyOnWrite();
        instance.setDayOfTheWeekValue(value);
        return this;
      }
      /**
       * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
       * @return The dayOfTheWeek.
       */
      @java.lang.Override
      public example.enumerations.EnumExample.DayOfTheWeek getDayOfTheWeek() {
        return instance.getDayOfTheWeek();
      }
      /**
       * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
       * @param value The enum numeric value on the wire for dayOfTheWeek to set.
       * @return This builder for chaining.
       */
      public Builder setDayOfTheWeek(example.enumerations.EnumExample.DayOfTheWeek value) {
        copyOnWrite();
        instance.setDayOfTheWeek(value);
        return this;
      }
      /**
       * <code>.example.enumerations.DayOfTheWeek day_of_the_week = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDayOfTheWeek() {
        copyOnWrite();
        instance.clearDayOfTheWeek();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.enumerations.EnumMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new example.enumerations.EnumExample.EnumMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "dayOfTheWeek_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\f" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<example.enumerations.EnumExample.EnumMessage> parser = PARSER;
          if (parser == null) {
            synchronized (example.enumerations.EnumExample.EnumMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<example.enumerations.EnumExample.EnumMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:example.enumerations.EnumMessage)
    private static final example.enumerations.EnumExample.EnumMessage DEFAULT_INSTANCE;
    static {
      EnumMessage defaultInstance = new EnumMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        EnumMessage.class, defaultInstance);
    }

    public static example.enumerations.EnumExample.EnumMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EnumMessage> PARSER;

    public static com.google.protobuf.Parser<EnumMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
